pipeline:
  debug:
    image: drone-registry.kernelpanic.co.za/android-image
    commands:
      - "chmod +x gradlew"
      - "./gradlew dependencies || true"
      - "bash ./gradlew assembleDebug"
  release:
    image: drone-registry.kernelpanic.co.za/android-image
    commands:
      - "chmod +x gradlew"
      - "./gradlew dependencies || true"
      - "bash ./gradlew assembleDebug"
