pipeline:
  debug:
    image: drone-registry.kernelpanic.co.za/android-image-sdk-27
    commands:
      - "chmod +x gradlew"
      - "./gradlew dependencies || true"
      - "org.gradle.daemon=false
      - "bash ./gradlew assembleDebug --no-daemon"
  unsignedrelease:
    image: drone-registry.kernelpanic.co.za/android-image-sdk-27
    commands:
      - "chmod +x gradlew"
      - "./gradlew dependencies || true"
      - "bash ./gradlew assembleRelease --no-daemon"
